// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TempMotoWeb.Data;

#nullable disable

namespace TempMotoWeb.Migrations
{
    [DbContext(typeof(TempMotoWebContext))]
    [Migration("20230926023154_AtualizarData")]
    partial class AtualizarData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TempMotoWeb.Models.Medicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Altitude")
                        .HasColumnType("real");

                    b.Property<DateTime?>("Data_Medicao")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("Num_Satelites")
                        .HasColumnType("int");

                    b.Property<float>("Temperatura")
                        .HasColumnType("real");

                    b.Property<float>("Umidade")
                        .HasColumnType("real");

                    b.Property<float>("Velocidade")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Medicao");
                });
#pragma warning restore 612, 618
        }
    }
}
